theme = "hex_steelV2"

[editor]
mouse = true
color-modes = true
popup-border = "all"
auto-format = true
text-width = 110
scrolloff = 10
auto-pairs = false
trim-final-newlines = true
trim-trailing-whitespace = true

[editor.whitespace]
render = "none"

[editor.whitespace.characters]
newline = "·"

[editor.cursor-shape]
insert = "underline"
normal = "block"
select = "block"

[editor.soft-wrap]
enable = true
max-wrap = 25
max-indent-retain = 0
wrap-indicator = ""
wrap-at-text-width = true

# s and d becomes navigation keys
# a replaces d as deletion
# w repaces a

[keys.insert]
"C-c" = "normal_mode"

[keys.normal]
s = ["page_cursor_half_down","goto_window_center"]
d = ["page_cursor_half_up","goto_window_center"]
A = "delete_char_backward"
a = "delete_selection"
H = "select_regex"
w = "append_mode"
W = "insert_at_line_end"
esc = ["keep_primary_selection", "collapse_selection"]
";" = "flip_selections"
"A-;" = "no_op"
"A-." = "no_op"
x = ["select_mode", "extend_line_below"]
X = ["select_mode", "extend_line_above"]

[keys.select]
s = ["page_cursor_half_down", "goto_window_center"]
d = ["page_cursor_half_up","goto_window_center"]
w = "append_mode"
W = "insert_at_line_end"
H = "select_regex"
esc = ["keep_primary_selection", "collapse_selection", "exit_select_mode"]
v = "extend_to_line_bounds"
";" = "flip_selections"
X = "extend_line_above"
"A-;" = "no_op"
"A-." = "no_op"
a = "delete_selection"
A = "delete_selection_noyank"

[keys.normal.g]
j = "goto_window_bottom"
k = "goto_window_top"
l = "goto_line_end_newline"

[keys.select.g]
j = "goto_window_bottom"
k = "goto_window_top"
l = "goto_line_end"

[keys.normal.space]
f = "file_picker_in_current_directory"
F = "file_picker"
K = "signature_help"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
auto-signature-help = false
