theme = "hex_steelV2"

[editor]
mouse = true
color-modes = true
popup-border = "all"
auto-format = true
text-width = 75
scrolloff = 10
auto-pairs = false
trim-final-newlines = true
trim-trailing-whitespace = true

[editor.whitespace]
render = "none"

[editor.whitespace.characters]
newline = "·"

[editor.cursor-shape]
insert = "underline"
normal = "block"
select = "block"

[editor.soft-wrap]
enable = false
max-wrap = 25
max-indent-retain = 0
wrap-indicator = ""
wrap-at-text-width = false

# s and d becomes navigation keys
# a replaces d as deletion
# w repaces a

[keys.insert]
"C-c" = "normal_mode"

[keys.normal]
s = "@6kzz"
a = "@6jzz"
H = "select_regex"
x = ["select_mode", "extend_line_below"]
X = ["select_mode", "extend_line_above"]

[keys.select]
s = "@6kzz"
a = "@6jzz"
H = "select_regex"
v = "extend_to_line_bounds"
X = "extend_line_above"

[keys.normal.g]
j = "goto_window_bottom"
k = "goto_window_top"
l = "goto_line_end_newline"

[keys.select.g]
j = "goto_window_bottom"
k = "goto_window_top"
l = "goto_line_end"

[keys.normal.space]
f = "file_picker_in_current_directory"
F = "file_picker"
K = "signature_help"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
auto-signature-help = false
