"comment" = { fg = "comment" }

"constant" = { fg = "gr1" }
"function" = { fg = "wh" }
"function.method" = { fg = "wh" }
"function.macro" = { fg = "wh" }
"keyword.storage.modifier" = { fg = "re" }
"keyword.control.import" = { fg = "t8" }
"keyword.control" = { fg = "t8" }
"keyword.function" = { fg = "re" }
"keyword" = { fg = "ye" }
"operator" = { fg = "t8" }
"punctuation" = { fg = "t9" }
"string" = { fg = "ye" }
"string.regexp" = { fg = "ye" }
"tag" = { fg = "t4" }
"type" = { fg = "t8", modifiers = ["bold"] }
"namespace" = { fg = "ye", modifiers = ["bold"] }
"variable" = { fg = "t4" }
"variable.parameter" = { fg = "ye" }
"variable.other.member" = { fg = "gr0" }
"label" = { fg = "t4" }

"diff.plus" = { fg = "diff_plus" }
"diff.delta" = { fg = "diff_delta" }
"diff.delta.moved" = { fg = "diff_delta_moved" }
"diff.minus" = { fg = "diff_minus" }

"ui.cursor.primary.insert" = { fg = "t2", bg = "highlight" }
"ui.cursor.primary.select" = { fg = "t2", bg = "highlight_two" }
"ui.cursor.primary" = { fg = "bl", bg = "highlight_three" }
"ui.cursor.match" = { fg = "highlight", bg = "bl", modifiers = ["bold"] }
"ui.cursorline.primary" = { bg = "ruler" }
"ui.cursorline.secondary" = { bg = "ruler" }

"ui.linenr" = { fg = "gr0", bg = "t2" }
"ui.linenr.selected" = { fg = "highlight_three", bg = "t2" }
"ui.gutter" = { bg = "t2" }

"ui.background" = { fg = "t4", bg = "t2" }
"ui.background.separator" = { fg = "gr0" }
"ui.help" = { fg = "t4", bg = "bl" }
"ui.menu" = { fg = "t4", bg = "bl" }
"ui.menu.selected" = { fg = "highlight_three", bg = "bl" }
"ui.popup" = { fg = "t4", bg = "bl" }
"ui.window" = { fg = "t4" }

"ui.selection" = { fg = "selection_fg", bg = "selection" }

"ui.statusline" = { fg = "t4", bg = "bl" }
"ui.statusline.inactive" = { fg = "t4", bg = "bl" }
"ui.statusline.normal" = { fg = "gr0", bg = "bl" }
"ui.statusline.insert" = { fg = "gr0", bg = "bl" }
"ui.statusline.select" = { fg = "highlight", bg = "t4" }

"ui.text" = { fg = "t4" }
"ui.text.focus" = { fg = "highlight_three", modifiers = ["bold"] }

"ui.virtual.ruler" = { bg = "ruler" }
"ui.virtual.indent-guide" = { fg = "gr0" }
"ui.virtual.whitespace" = { fg = "gr0" }
"ui.virtual.jump-label" = { fg = "re", modifiers = ["bold"] }
"ui.virtual.inlay-hint" = { fg = "hints", modifiers = ["bold"] }

"ui.bufferline" = { fg = "gr0", bg = "black" }
"ui.bufferline.active" = { fg = "t7", bg = "t2" }

"diagnostic.error" = { underline = { color = "error", style = "curl" } }
"diagnostic.warning" = { underline = { color = "warning", style = "curl" } }
"diagnostic.info" = { underline = { color = "info", style = "curl" } }
"diagnostic.hint" = { underline = { color = "display", style = "curl" } }

"error" = { fg = "error", modifiers = ["bold"] }
"warning" = { fg = "warning", modifiers = ["bold"] }
"info" = { fg = "info", modifiers = ["bold"] }
"hint" = { fg = "display", modifiers = ["bold"] }
"special" = { fg = "t7", modifiers = ["bold"] }

"markup.heading" = { fg = "t7" }
"markup.list" = { fg = "t7" }
"markup.bold" = { fg = "t4" }
"markup.italic" = { fg = "t4" }
"markup.strikethrough" = { fg = "t4", modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "re", modifiers = ["underlined"] }
"markup.link.text" = { fg = "re" }
"markup.quote" = { fg = "gr1" }
"markup.raw" = { fg = "t4" }

[palette]
selection_fg = "#9dc183"

hints = "#31353c"
ruler  = "#222320"

bl = "#0e0e0d" # black
t2 = "#1A1A1A" # Background
gr0 = "#909090" # grey
t4 = "#A0A0A0" # foreground
gr1 = "#C0C0C0" # grey2
ye = "#d4c69f" # beige
gn = "#9dc183" # green
t8 = "#9bc1bb" # teal
t9 = "#b5c5c5" # less teal
re = "#E86060" # red
wh = "#E0E0E0" # white

highlight = "#dec683" #yellow
highlight_two = "#f69c3c" #orange
highlight_three = "#dec683" #mustard

selection = "#303030"

black = "#000000"
comment = "#707070"
comment_doc = "#202020"

error   = "#e8403a"
warning = "#ffbf00"
display = "#42baff"
info = "#dad7d5"

diff_minus = "#e8403a"
diff_delta = "#dec683"
diff_plus = "#4db066"
diff_delta_moved = "#dec683"
