foreground            #A0A0A0
background            #161616
selection_foreground  #DEC683
selection_background  #404040
url_color             #DEC683
cursor                #DEC683

# black
color0   #000000
color8   #404040

# red
color1   #E86060
color9   #E4544D

# green
# color2   #A8CBA4
color2   #9DC183
color10  #99BE70

# yellow
color3   #D4C69F
color11  #DEC683

# blue
color4   #C0D0CE
color12  #9BC1BB

# gray0
color5   #909090
color13  #A0A0A0

# gray1
color6   #D0D0D0
color14  #A0A0A0

# white
color7   #FFFFFF
color15  #C0C0C0
