foreground            #A0A0A0
background            #1A1A1A
selection_foreground  #dec683
selection_background  #404040
url_color             #dec683
cursor                #dec683

# black
color0   #000000
color8   #404040

# red
color1   #E87070
color9   #e4544d

# green
color2   #9dc183
color10  #99be70

# yellow
color3   #d4c69f
color11  #dec683

# blue
color4   #c0d0ce
color12  #9bc1bb

# gray0
color5   #909090
color13  #A0A0A0

# gray1
color6   #D0D0D0
color14  #A0A0A0

# white
color7   #FFFFFF
color15  #C0C0C0
